name: Build NimbusOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src, llvm-tools-preview

    - name: Install bootimage
      run: cargo install bootimage

    - name: Build Kernel image
      run: cargo bootimage

    - name: Rename image
      run: mv target/x86_64-nimbus_os/debug/bootimage-NimbusOS.bin bootimage-NimbusOS.bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nimbus-os-binary
        path: |
          bootimage-NimbusOS.bin
          index.html
